packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - tegami@0.1.3
  - '@fuma-translate/react@1.0.2'
  - fumadocs-core@16.10.2
  - fumadocs-ui@16.10.2
  - fumapress@0.6.1
